// Generated by Supabase MCP (generate_typescript_types) for project nkefzhgleymxhifpgfcn.
// DO NOT EDIT by hand — regenerate via MCP if schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admin_audit_log: {
        Row: {
          action: string
          actor_id: string
          created_at: string
          id: string
          payload: Json | null
          target_id: string
          target_type: string
        }
        Insert: {
          action: string
          actor_id: string
          created_at?: string
          id?: string
          payload?: Json | null
          target_id: string
          target_type: string
        }
        Update: {
          action?: string
          actor_id?: string
          created_at?: string
          id?: string
          payload?: Json | null
          target_id?: string
          target_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      affiliate_codes: {
        Row: {
          active: boolean
          affiliate_id: string
          code: string
          created_at: string
          discount_pct: number
          expires_at: string | null
          id: string
        }
        Insert: {
          active?: boolean
          affiliate_id: string
          code: string
          created_at?: string
          discount_pct: number
          expires_at?: string | null
          id?: string
        }
        Update: {
          active?: boolean
          affiliate_id?: string
          code?: string
          created_at?: string
          discount_pct?: number
          expires_at?: string | null
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "affiliate_codes_affiliate_id_fkey"
            columns: ["affiliate_id"]
            isOneToOne: false
            referencedRelation: "affiliates"
            referencedColumns: ["id"]
          },
        ]
      }
      affiliates: {
        Row: {
          active: boolean
          commission_pct: number | null
          created_at: string
          email: string | null
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          active?: boolean
          commission_pct?: number | null
          created_at?: string
          email?: string | null
          id?: string
          name: string
          updated_at?: string
        }
        Update: {
          active?: boolean
          commission_pct?: number | null
          created_at?: string
          email?: string | null
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      gbp_notifications: {
        Row: {
          entry_client_id: number | null
          id: number
          invoice_id: string | null
          message: string
          processed_at: string | null
          pulled_at: string
          time_created: string | null
        }
        Insert: {
          entry_client_id?: number | null
          id: number
          invoice_id?: string | null
          message: string
          processed_at?: string | null
          pulled_at?: string
          time_created?: string | null
        }
        Update: {
          entry_client_id?: number | null
          id?: number
          invoice_id?: string | null
          message?: string
          processed_at?: string | null
          pulled_at?: string
          time_created?: string | null
        }
        Relationships: []
      }
      order_items: {
        Row: {
          created_at: string
          id: string
          line_total_cents: number
          order_id: string
          product_name: string
          product_slug: string
          quantity: number
          strength_label: string
          unit_price_cents: number
        }
        Insert: {
          created_at?: string
          id?: string
          line_total_cents: number
          order_id: string
          product_name: string
          product_slug: string
          quantity: number
          strength_label: string
          unit_price_cents: number
        }
        Update: {
          created_at?: string
          id?: string
          line_total_cents?: number
          order_id?: string
          product_name?: string
          product_slug?: string
          quantity?: number
          strength_label?: string
          unit_price_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_messages: {
        Row: {
          author_id: string
          author_role: string
          body: string
          created_at: string
          id: string
          order_id: string
        }
        Insert: {
          author_id: string
          author_role: string
          body: string
          created_at?: string
          id?: string
          order_id: string
        }
        Update: {
          author_id?: string
          author_role?: string
          body?: string
          created_at?: string
          id?: string
          order_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_messages_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_messages_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          affiliate_id: string | null
          applied_code_id: string | null
          created_at: string
          discount_cents: number
          gbp_check_id: string | null
          gbp_invoice_id: string | null
          gbp_last_polled_at: string | null
          gbp_paid_at: string | null
          gbp_payment_result: number | null
          id: string
          notes_internal: string | null
          order_number: number
          shipping_address: Json
          status: string
          subtotal_cents: number
          total_cents: number
          tracking_carrier: string | null
          tracking_number: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          affiliate_id?: string | null
          applied_code_id?: string | null
          created_at?: string
          discount_cents?: number
          gbp_check_id?: string | null
          gbp_invoice_id?: string | null
          gbp_last_polled_at?: string | null
          gbp_paid_at?: string | null
          gbp_payment_result?: number | null
          id?: string
          notes_internal?: string | null
          order_number?: number
          shipping_address: Json
          status?: string
          subtotal_cents?: number
          total_cents?: number
          tracking_carrier?: string | null
          tracking_number?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          affiliate_id?: string | null
          applied_code_id?: string | null
          created_at?: string
          discount_cents?: number
          gbp_check_id?: string | null
          gbp_invoice_id?: string | null
          gbp_last_polled_at?: string | null
          gbp_paid_at?: string | null
          gbp_payment_result?: number | null
          id?: string
          notes_internal?: string | null
          order_number?: number
          shipping_address?: Json
          status?: string
          subtotal_cents?: number
          total_cents?: number
          tracking_carrier?: string | null
          tracking_number?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_affiliate_id_fkey"
            columns: ["affiliate_id"]
            isOneToOne: false
            referencedRelation: "affiliates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_applied_code_id_fkey"
            columns: ["applied_code_id"]
            isOneToOne: false
            referencedRelation: "affiliate_codes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      product_prices: {
        Row: {
          active: boolean
          created_at: string
          currency: string
          id: string
          price_cents: number
          product_slug: string
          strength_label: string
          updated_at: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          currency?: string
          id?: string
          price_cents: number
          product_slug: string
          strength_label: string
          updated_at?: string
        }
        Update: {
          active?: boolean
          created_at?: string
          currency?: string
          id?: string
          price_cents?: number
          product_slug?: string
          strength_label?: string
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          email: string
          full_name: string | null
          id: string
          phone: string | null
          referred_by_affiliate_id: string | null
          referred_by_code_id: string | null
          role: string
          shipping_address: Json | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          email: string
          full_name?: string | null
          id: string
          phone?: string | null
          referred_by_affiliate_id?: string | null
          referred_by_code_id?: string | null
          role?: string
          shipping_address?: Json | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string
          full_name?: string | null
          id?: string
          phone?: string | null
          referred_by_affiliate_id?: string | null
          referred_by_code_id?: string | null
          role?: string
          shipping_address?: Json | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_referred_by_affiliate_id_fkey"
            columns: ["referred_by_affiliate_id"]
            isOneToOne: false
            referencedRelation: "affiliates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_referred_by_code_id_fkey"
            columns: ["referred_by_code_id"]
            isOneToOne: false
            referencedRelation: "affiliate_codes"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      create_order_with_items: {
        Args: { p_code: string; p_items: Json; p_shipping: Json }
        Returns: {
          discount_cents: number
          order_id: string
          subtotal_cents: number
          total_cents: number
        }[]
      }
      is_admin: { Args: never; Returns: boolean }
      validate_affiliate_code: {
        Args: { p_code: string }
        Returns: {
          discount_pct: number
          valid: boolean
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
